### ISSUE TITLE
navystack - rhymix 질문

### ISSUE THREAD

**Issue by imageschool** [Navystack/rhymix#10]
@NavyStack 

https://askfront.com/topic/41/navystack-rhymix-%EC%A7%88%EB%AC%B8

**Comment by NavyStack** [comment]
@imageschool 
https://askfront.com/topic/41/navystack-rhymix-%EC%A7%88%EB%AC%B8/2

**Comment by imageschool** [comment]
@NavyStack 답변 감사합니다. https://askfront.com/topic/41/navystack-rhymix-%EC%A7%88%EB%AC%B8/4

**Comment by NavyStack** [comment]
DNS 서비스의 프록시 설정과 관련된 오류였습니다.
해당 이슈를 종료합니다.

**Comment by imageschool** [comment]
감사합니다.
